[package]
name = "small-world-threaded"
version.workspace = true
edition.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
rand = { version = "0.8", default-features = false, features = ["alloc"] }
rand_chacha = { version = "0.3", default-features = false }
rayon = { workspace = true, optional = true }
